name: Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_WITH: maintenance
      with:
        ruby-version: ruby-head
        bundler-cache: true
    
    - name: Installing packages
      run: sudo apt-get install wget
    
    - name: Generate documentation
      timeout-minutes: 5
      run: bundle exec bake utopia:project:static
    
    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: docs
        folder: docs
