name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm
  IO_EVENT_SELECTOR: Select

jobs:
  test:
    name: ${{matrix.name}} on ubuntu / IO_EVENT_SELECTOR=Select
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: combined copy loop
            command: for i in $(seq 1 50); do echo "::group::combined copy iteration $i"; timeout 30s bundle exec sus test/process/task_suite_then_fork.rb; echo "::endgroup::"; done
          - name: task then fork loop
            command: for i in $(seq 1 50); do echo "::group::task then fork iteration $i"; timeout 30s bundle exec sus test/async/task.rb test/process/fork.rb; echo "::endgroup::"; done
    
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true
    
    - name: Run selected tests
      timeout-minutes: 5
      run: ${{matrix.command}}
    
    # Maybe buggy.
    # - name: Run external tests
    #   timeout-minutes: 10
    #   run: bundle exec bake test:external
