name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu
          # - macos
        
        ruby: 
          - 2.3
          - 2.4
          - 2.5
          - 2.6
        
        include:
          - os: 'ubuntu'
            ruby: '2.6'
            env: COVERAGE=PartialSummary,Coveralls
    
    runs-on: ${{matrix.os}}-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: ${{matrix.env}} bundle exec rspec
    - name: Run external tests
      run: bundle exec rake external
