name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm
  IO_EVENT_SELECTOR: Select

jobs:
  test:
    name: ${{matrix.name}} on ubuntu / IO_EVENT_SELECTOR=Select
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: fork only
            command: bundle exec sus test/process/fork.rb
          - name: task only
            command: bundle exec sus test/async/task.rb
          - name: task then fork
            command: bundle exec sus test/async/task.rb test/process/fork.rb
          - name: async dir
            command: bundle exec sus test/async
          - name: async dir then fork
            command: bundle exec sus test/async test/process/fork.rb
          - name: kernel dir then fork
            command: bundle exec sus test/kernel test/kernel.rb test/process/fork.rb
          - name: sorted task through fork
            command: files=$(find test -type f -name '*.rb' | sort | awk '$0 >= "test/async/task.rb" && $0 <= "test/process/fork.rb" {print}'); bundle exec sus $files
          - name: sorted prefix through fork
            command: files=$(find test -type f -name '*.rb' | sort | awk '$0 <= "test/process/fork.rb" {print}'); bundle exec sus $files
          - name: full suite
            command: bundle exec bake test
    
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true
    
    - name: Run selected tests
      timeout-minutes: 5
      run: ${{matrix.command}}
    
    # Maybe buggy.
    # - name: Run external tests
    #   timeout-minutes: 10
    #   run: bundle exec bake test:external
