name: Test Agent Context

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Agent Context
    runs-on: ubuntu-latest
    
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
    
    - name: Pull Model
      run: bundle exec bake async:ollama:pull
    
    - name: Run tests
      timeout-minutes: 30
      run: bundle exec sus test/.agent/context
